package e.otatt.drugsrxgood;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity
public class Drugs {
    @PrimaryKey
    int p_id;

    @ColumnInfo(name="medication")
    String medication;

    @ColumnInfo(name="dosage")
    String dosage;

    @ColumnInfo(name="frequency")
    String frequency;

    @ColumnInfo(name="refill")
    String refill;

    @ColumnInfo(name="isActive")
    boolean isActive;

    //foreign_key is the autogenerated p_id from Users db
    @ColumnInfo(name="foreign_key")
    String foreign_key;

    public Drugs(int p_id, String medication,
                 String dosage, String frequency, String refill,
                 boolean active, String foreign_key) {
        this.p_id = p_id;
        this.medication = medication;
        this.dosage = dosage;
        this.frequency = frequency;
        this.refill = refill;
        this.isActive = true;
        this.foreign_key = foreign_key;
    }

    public int getP_id() {
        return p_id;
    }

    public void setP_id(int p_id) {
        this.p_id = p_id;
    }

    public String getMedication() {
        return medication;
    }

    public void setMedication(String medication) {
        this.medication = medication;
    }

    public String getDosage() {
        return dosage;
    }

    public void setDosage(String dosage) {
        this.dosage = dosage;
    }

    public String getFrequency() {
        return frequency;
    }

    public void setFrequency(String frequency) {
        this.frequency = frequency;
    }

    public String getRefill() {
        return refill;
    }

    public void setRefill(String refill) {
        this.refill = refill;
    }

    public boolean isActive() {
        return isActive;
    }

    public void setActive(boolean active) {
        this.isActive = active;
    }

    public String getForeign_key() {
        return foreign_key;
    }

    public void setForeign_key(String foreign_key) {
        this.foreign_key = foreign_key;
    }

}
